import assert from "node:assert/strict";import test from "node:test";import * as vscode from "vscode";import {encodeRequest} from "../src/responses/request.js";
const tool={name:"read",description:"Read a file",inputSchema:{type:"object",properties:{path:{type:"string"}},required:["path"]}};
test("multi-turn Agent history and required tools use exact Responses items",()=>{const messages=[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("do both")]},{role:vscode.LanguageModelChatMessageRole.Assistant,name:undefined,content:[new vscode.LanguageModelTextPart("working"),new vscode.LanguageModelToolCallPart("a","read",{path:"a"}),new vscode.LanguageModelToolCallPart("b","read",{path:"b"})]},{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelToolResultPart("a",[new vscode.LanguageModelTextPart("A")]),new vscode.LanguageModelToolResultPart("b",[new vscode.LanguageModelTextPart("B")])]}];const request=encodeRequest("code",messages,{toolMode:vscode.LanguageModelChatToolMode.Required,tools:[tool]});assert.deepEqual(request.input,[{type:"message",role:"user",content:[{type:"input_text",text:"do both"}]},{type:"message",role:"assistant",content:[{type:"output_text",text:"working"}]},{type:"function_call",call_id:"a",name:"read",arguments:'{"path":"a"}'},{type:"function_call",call_id:"b",name:"read",arguments:'{"path":"b"}'},{type:"function_call_output",call_id:"a",output:[{type:"input_text",text:"A"}]},{type:"function_call_output",call_id:"b",output:[{type:"input_text",text:"B"}]}]);assert.deepEqual(request.tools,[{type:"function",name:"read",description:"Read a file",parameters:tool.inputSchema}]);assert.equal(request.tool_choice,"required");});

test("automatic tool policy is emitted only with declared tools",()=>{const message={role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("inspect")]};const withTools=encodeRequest("code",[message],{toolMode:vscode.LanguageModelChatToolMode.Auto,tools:[tool]});assert.equal(withTools.tool_choice,"auto");assert.equal(withTools.tools?.length,1);const textOnly=encodeRequest("code",[message],{toolMode:vscode.LanguageModelChatToolMode.Auto});assert.equal(textOnly.tool_choice,undefined);assert.equal(textOnly.tools,undefined);});

test("required tool policy without a declared tool fails at the adapter boundary",()=>{assert.throws(()=>encodeRequest("code",[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("inspect")]}],{toolMode:vscode.LanguageModelChatToolMode.Required,tools:[]}),/requires at least one declared tool/);});

test("named messages fail instead of erasing participant identity",()=>{assert.throws(()=>encodeRequest("code",[{role:vscode.LanguageModelChatMessageRole.User,name:"alice",content:[new vscode.LanguageModelTextPart("hello")]}],{toolMode:vscode.LanguageModelChatToolMode.Auto}),/Named VS Code messages are not supported/);});

test("supported image input is exact and unsupported media fails locally",()=>{const request=encodeRequest("vision",[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("inspect"),vscode.LanguageModelDataPart.image(Uint8Array.of(1,2,3),"image/webp")]}],{toolMode:vscode.LanguageModelChatToolMode.Auto});assert.deepEqual(request.input,[{type:"message",role:"user",content:[{type:"input_text",text:"inspect"},{type:"input_image",image_url:"data:image/webp;base64,AQID"}]}]);assert.throws(()=>encodeRequest("vision",[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[vscode.LanguageModelDataPart.image(Uint8Array.of(1),"image/gif")]}],{toolMode:vscode.LanguageModelChatToolMode.Auto}),/Unsupported data part: image\/gif/);});

test("tool output retains adjacent text boundaries and ordered images",()=>{
 const output=[new vscode.LanguageModelTextPart("before"),vscode.LanguageModelDataPart.image(Uint8Array.of(1,2,3),"image/png"),new vscode.LanguageModelTextPart("after"),new vscode.LanguageModelTextPart("tail")];
 const request=encodeRequest("images",[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelToolResultPart("call_image",output)]}],{toolMode:vscode.LanguageModelChatToolMode.Auto});
 assert.deepEqual(request.input,[{type:"function_call_output",call_id:"call_image",output:[{type:"input_text",text:"before"},{type:"input_image",image_url:"data:image/png;base64,AQID"},{type:"input_text",text:"after"},{type:"input_text",text:"tail"}]}]);
});
