import assert from "node:assert/strict";import test from "node:test";import * as vscode from "vscode";import {encodeRequest} from "../src/responses/request.js";
const tool={name:"read",description:"Read a file",inputSchema:{type:"object",properties:{path:{type:"string"}},required:["path"]}};
test("multi-turn Agent history and required tools use exact Responses items",()=>{const messages=[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("do both")]},{role:vscode.LanguageModelChatMessageRole.Assistant,name:undefined,content:[new vscode.LanguageModelTextPart("working"),new vscode.LanguageModelToolCallPart("a","read",{path:"a"}),new vscode.LanguageModelToolCallPart("b","read",{path:"b"})]},{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelToolResultPart("a",[new vscode.LanguageModelTextPart("A")]),new vscode.LanguageModelToolResultPart("b",[new vscode.LanguageModelTextPart("B")])]}];const request=encodeRequest("work/code","code",messages,{toolMode:vscode.LanguageModelChatToolMode.Required,tools:[tool]});assert.deepEqual(request.input,[{type:"message",role:"user",content:[{type:"input_text",text:"do both"}]},{type:"message",role:"assistant",content:[{type:"output_text",text:"working"}]},{type:"function_call",call_id:"a",name:"read",arguments:'{"path":"a"}'},{type:"function_call",call_id:"b",name:"read",arguments:'{"path":"b"}'},{type:"function_call_output",call_id:"a",output:[{type:"input_text",text:"A"}]},{type:"function_call_output",call_id:"b",output:[{type:"input_text",text:"B"}]}]);assert.deepEqual(request.tools,[{type:"function",name:"read",description:"Read a file",parameters:tool.inputSchema}]);assert.equal(request.tool_choice,"required");});

test("automatic tool policy is emitted only with declared tools",()=>{const message={role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("inspect")]};const withTools=encodeRequest("work/code","code",[message],{toolMode:vscode.LanguageModelChatToolMode.Auto,tools:[tool]});assert.equal(withTools.tool_choice,"auto");assert.equal(withTools.tools?.length,1);const textOnly=encodeRequest("work/code","code",[message],{toolMode:vscode.LanguageModelChatToolMode.Auto});assert.equal(textOnly.tool_choice,undefined);assert.equal(textOnly.tools,undefined);});

test("VS Code Agent system instructions remain system messages",()=>{const request=encodeRequest("work/code","code",[{role:3 as vscode.LanguageModelChatMessageRole,name:undefined,content:[new vscode.LanguageModelTextPart("Use tools carefully.")]}],{toolMode:vscode.LanguageModelChatToolMode.Auto});assert.deepEqual(request.input,[{type:"message",role:"system",content:[{type:"input_text",text:"Use tools carefully."}]}]);});

test("VS Code Agent embedded stateful marker resumes after the marked response",()=>{const marker=new vscode.LanguageModelDataPart(new TextEncoder().encode("work/code\\swobu_resp_1"),"stateful_marker"),request=encodeRequest("work/code","code",[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("old request")]},{role:vscode.LanguageModelChatMessageRole.Assistant,name:undefined,content:[marker,new vscode.LanguageModelTextPart("working"),new vscode.LanguageModelToolCallPart("call_1","read",{path:"a"})]},{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelToolResultPart("call_1",[new vscode.LanguageModelTextPart("A")])]}],{toolMode:vscode.LanguageModelChatToolMode.Auto});assert.equal(request.previous_response_id,"swobu_resp_1");assert.deepEqual(request.input,[{type:"function_call_output",call_id:"call_1",output:[{type:"input_text",text:"A"}]}]);});

test("VS Code Agent uses only a marker belonging to the selected model",()=>{const marker=new vscode.LanguageModelDataPart(new TextEncoder().encode("other/code\\swobu_resp_1"),"stateful_marker"),request=encodeRequest("work/code","code",[{role:vscode.LanguageModelChatMessageRole.Assistant,name:undefined,content:[marker,new vscode.LanguageModelTextPart("other model response")]},{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("new request")]}],{toolMode:vscode.LanguageModelChatToolMode.Auto});assert.equal(request.previous_response_id,undefined);assert.deepEqual(request.input,[{type:"message",role:"assistant",content:[{type:"output_text",text:"other model response"}]},{type:"message",role:"user",content:[{type:"input_text",text:"new request"}]}]);});

test("VS Code Agent rejects malformed or non-assistant stateful markers",()=>{for(const value of ["work/code","\\swobu_resp_1","work/code\\"]){const marker=new vscode.LanguageModelDataPart(new TextEncoder().encode(value),"stateful_marker");assert.throws(()=>encodeRequest("work/code","code",[{role:vscode.LanguageModelChatMessageRole.Assistant,name:undefined,content:[marker]}],{toolMode:vscode.LanguageModelChatToolMode.Auto}),/Invalid VS Code stateful marker/);}const marker=new vscode.LanguageModelDataPart(new TextEncoder().encode("work/code\\swobu_resp_1"),"stateful_marker");assert.throws(()=>encodeRequest("work/code","code",[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[marker]}],{toolMode:vscode.LanguageModelChatToolMode.Auto}),/Invalid VS Code stateful marker/);});

test("VS Code Agent chooses the newest matching embedded marker",()=>{const marker=(id:string)=>new vscode.LanguageModelDataPart(new TextEncoder().encode(`work/code\\${id}`),"stateful_marker"),request=encodeRequest("work/code","code",[{role:vscode.LanguageModelChatMessageRole.Assistant,name:undefined,content:[marker("resp_1"),new vscode.LanguageModelTextPart("old")]},{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("middle")]},{role:vscode.LanguageModelChatMessageRole.Assistant,name:undefined,content:[new vscode.LanguageModelTextPart("latest"),marker("resp_2")]},{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("continue")]}],{toolMode:vscode.LanguageModelChatToolMode.Auto});assert.equal(request.previous_response_id,"resp_2");assert.deepEqual(request.input,[{type:"message",role:"user",content:[{type:"input_text",text:"continue"}]}]);});

test("required tool policy without a declared tool fails at the adapter boundary",()=>{assert.throws(()=>encodeRequest("work/code","code",[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("inspect")]}],{toolMode:vscode.LanguageModelChatToolMode.Required,tools:[]}),/requires at least one declared tool/);});

test("named messages fail instead of erasing participant identity",()=>{assert.throws(()=>encodeRequest("work/code","code",[{role:vscode.LanguageModelChatMessageRole.User,name:"alice",content:[new vscode.LanguageModelTextPart("hello")]}],{toolMode:vscode.LanguageModelChatToolMode.Auto}),/Named VS Code messages are not supported/);});

test("VS Code Agent empty tool-result message name is not participant identity",()=>{const request=encodeRequest("work/code","code",[{role:vscode.LanguageModelChatMessageRole.User,name:"",content:[new vscode.LanguageModelToolResultPart("call_1",[new vscode.LanguageModelTextPart("result")])]}],{toolMode:vscode.LanguageModelChatToolMode.Auto});assert.deepEqual(request.input,[{type:"function_call_output",call_id:"call_1",output:[{type:"input_text",text:"result"}]}]);});

test("supported image input is exact and unsupported media fails locally",()=>{const request=encodeRequest("work/vision","vision",[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelTextPart("inspect"),vscode.LanguageModelDataPart.image(Uint8Array.of(1,2,3),"image/webp")]}],{toolMode:vscode.LanguageModelChatToolMode.Auto});assert.deepEqual(request.input,[{type:"message",role:"user",content:[{type:"input_text",text:"inspect"},{type:"input_image",image_url:"data:image/webp;base64,AQID"}]}]);assert.throws(()=>encodeRequest("work/vision","vision",[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[vscode.LanguageModelDataPart.image(Uint8Array.of(1),"image/gif")]}],{toolMode:vscode.LanguageModelChatToolMode.Auto}),/Unsupported data part: image\/gif/);});

test("tool output retains adjacent text boundaries and ordered images",()=>{
 const output=[new vscode.LanguageModelTextPart("before"),vscode.LanguageModelDataPart.image(Uint8Array.of(1,2,3),"image/png"),new vscode.LanguageModelTextPart("after"),new vscode.LanguageModelTextPart("tail")];
 const request=encodeRequest("work/images","images",[{role:vscode.LanguageModelChatMessageRole.User,name:undefined,content:[new vscode.LanguageModelToolResultPart("call_image",output)]}],{toolMode:vscode.LanguageModelChatToolMode.Auto});
 assert.deepEqual(request.input,[{type:"function_call_output",call_id:"call_image",output:[{type:"input_text",text:"before"},{type:"input_image",image_url:"data:image/png;base64,AQID"},{type:"input_text",text:"after"},{type:"input_text",text:"tail"}]}]);
});
