import {readFileSync,writeFileSync,mkdirSync} from "node:fs";
const keys=["Open","Set Up","Connect Claude Code","Connect Codex","Configure Model","Refresh Models","Images","Tool calling","Context window","Max output","Reset overrides","Default","On","Off","Custom…","Choose a Swobu route","Enter a positive integer","Default · {0}","Set up Swobu","Manage Language Models","Swobu routes are ready. Select one in Manage Language Models.","Use your Swobu routes in VS Code","Install Swobu","Swobu is not installed on this extension host.","Swobu is required to provide language models.","Could not download the official Swobu installer (HTTP {0}).","Swobu did not become ready. Check the Swobu terminal for details.","The configured Swobu executable was not found: {0}","Create a Swobu workspace first.","Workspace for {0}"];
const errorKeys=["Swobu endpoint must use HTTP or HTTPS.","Swobu endpoint must be loopback.","Swobu endpoint must be a loopback origin without credentials, a path, a query, or a fragment.","The configured Swobu executable must be an absolute path on this extension host.","Swobu returned no response stream.","Swobu connect exited with code {0}.","Swobu request failed (HTTP {0}).","Unsupported VS Code language-model part: {0}.","Unsupported VS Code message role.","Unsupported data part: {0}.","Unsupported tool result part.","Expected a boolean model advertisement.","Expected a positive integer model advertisement.","Swobu returned malformed streaming JSON.","Function call is missing its call ID.","Tool arguments arrived before their function call.","Completed function call has no streaming state.","Swobu request failed.","Streaming tool event is missing its output index."];
keys.push(...errorKeys);
const translations={
 "zh-cn":["打开","设置","连接 Claude Code","连接 Codex","配置模型","刷新模型","图像","工具调用","上下文窗口","最大输出","重置覆盖设置","默认","开","关","自定义…","选择 Swobu 路由","请输入正整数","默认 · {0}","设置 Swobu","管理语言模型","Swobu 路由已就绪。请在管理语言模型中选择。","在 VS Code 中使用 Swobu 路由"],
 ja:["開く","セットアップ","Claude Code に接続","Codex に接続","モデルを設定","モデルを更新","画像","ツール呼び出し","コンテキスト長","最大出力","上書きをリセット","既定","オン","オフ","カスタム…","Swobu ルートを選択","正の整数を入力","既定 · {0}","Swobu をセットアップ","言語モデルの管理","Swobu ルートの準備ができました。言語モデルの管理で選択してください。","VS Code で Swobu ルートを使用"],
 "pt-br":["Abrir","Configurar","Conectar Claude Code","Conectar Codex","Configurar modelo","Atualizar modelos","Imagens","Chamada de ferramentas","Janela de contexto","Saída máxima","Redefinir substituições","Padrão","Ativado","Desativado","Personalizado…","Escolha uma rota Swobu","Digite um inteiro positivo","Padrão · {0}","Configurar Swobu","Gerenciar modelos de linguagem","As rotas Swobu estão prontas. Selecione uma em Gerenciar modelos de linguagem.","Use suas rotas Swobu no VS Code"],
 id:["Buka","Siapkan","Hubungkan Claude Code","Hubungkan Codex","Konfigurasi model","Segarkan model","Gambar","Pemanggilan alat","Jendela konteks","Keluaran maksimum","Atur ulang penyesuaian","Default","Aktif","Nonaktif","Kustom…","Pilih rute Swobu","Masukkan bilangan bulat positif","Default · {0}","Siapkan Swobu","Kelola model bahasa","Rute Swobu siap. Pilih satu di Kelola model bahasa.","Gunakan rute Swobu di VS Code"],
 ko:["열기","설정","Claude Code 연결","Codex 연결","모델 구성","모델 새로 고침","이미지","도구 호출","컨텍스트 창","최대 출력","재정의 초기화","기본값","켜기","끄기","사용자 지정…","Swobu 경로 선택","양의 정수 입력","기본값 · {0}","Swobu 설정","언어 모델 관리","Swobu 경로가 준비되었습니다. 언어 모델 관리에서 선택하세요.","VS Code에서 Swobu 경로 사용"],
 es:["Abrir","Configurar","Conectar Claude Code","Conectar Codex","Configurar modelo","Actualizar modelos","Imágenes","Llamadas a herramientas","Ventana de contexto","Salida máxima","Restablecer ajustes","Predeterminado","Activado","Desactivado","Personalizado…","Elige una ruta Swobu","Introduce un entero positivo","Predeterminado · {0}","Configurar Swobu","Administrar modelos de lenguaje","Las rutas Swobu están listas. Selecciona una en Administrar modelos de lenguaje.","Usa tus rutas Swobu en VS Code"],
 de:["Öffnen","Einrichten","Claude Code verbinden","Codex verbinden","Modell konfigurieren","Modelle aktualisieren","Bilder","Werkzeugaufrufe","Kontextfenster","Maximale Ausgabe","Anpassungen zurücksetzen","Standard","Ein","Aus","Benutzerdefiniert…","Swobu-Route auswählen","Positive ganze Zahl eingeben","Standard · {0}","Swobu einrichten","Sprachmodelle verwalten","Swobu-Routen sind bereit. Wähle eine unter Sprachmodelle verwalten aus.","Swobu-Routen in VS Code verwenden"],
 fr:["Ouvrir","Configurer","Connecter Claude Code","Connecter Codex","Configurer le modèle","Actualiser les modèles","Images","Appels d’outils","Fenêtre de contexte","Sortie maximale","Réinitialiser les réglages","Par défaut","Activé","Désactivé","Personnalisé…","Choisissez une route Swobu","Saisissez un entier positif","Par défaut · {0}","Configurer Swobu","Gérer les modèles de langage","Les routes Swobu sont prêtes. Sélectionnez-en une dans Gérer les modèles de langage.","Utilisez vos routes Swobu dans VS Code"],
 ru:["Открыть","Настроить","Подключить Claude Code","Подключить Codex","Настроить модель","Обновить модели","Изображения","Вызов инструментов","Контекстное окно","Максимальный вывод","Сбросить переопределения","По умолчанию","Вкл.","Выкл.","Другое…","Выберите маршрут Swobu","Введите положительное целое число","По умолчанию · {0}","Настроить Swobu","Управление языковыми моделями","Маршруты Swobu готовы. Выберите маршрут в управлении языковыми моделями.","Используйте маршруты Swobu в VS Code"],
 uk:["Відкрити","Налаштувати","Підключити Claude Code","Підключити Codex","Налаштувати модель","Оновити моделі","Зображення","Виклики інструментів","Контекстне вікно","Максимальний вивід","Скинути перевизначення","Типово","Увімкнено","Вимкнено","Власне…","Виберіть маршрут Swobu","Введіть додатне ціле число","Типово · {0}","Налаштувати Swobu","Керування мовними моделями","Маршрути Swobu готові. Виберіть маршрут у керуванні мовними моделями.","Використовуйте маршрути Swobu у VS Code"]
};
const added={
 "zh-cn":["安装 Swobu","此扩展主机上未安装 Swobu。","需要 Swobu 才能提供语言模型。","无法下载官方 Swobu 安装程序（HTTP {0}）。","Swobu 未能就绪。请查看 Swobu 终端了解详情。","找不到配置的 Swobu 可执行文件：{0}","请先创建 Swobu 工作区。","{0} 的工作区"],
 ja:["Swobu をインストール","この拡張機能ホストには Swobu がインストールされていません。","言語モデルを提供するには Swobu が必要です。","公式 Swobu インストーラーをダウンロードできませんでした（HTTP {0}）。","Swobu の準備ができませんでした。詳細は Swobu ターミナルを確認してください。","設定された Swobu 実行ファイルが見つかりません：{0}","最初に Swobu ワークスペースを作成してください。","{0} 用ワークスペース"],
 "pt-br":["Instalar Swobu","O Swobu não está instalado neste host de extensão.","O Swobu é necessário para fornecer modelos de linguagem.","Não foi possível baixar o instalador oficial do Swobu (HTTP {0}).","O Swobu não ficou pronto. Consulte o terminal do Swobu para obter detalhes.","O executável Swobu configurado não foi encontrado: {0}","Crie primeiro um espaço de trabalho do Swobu.","Espaço de trabalho para {0}"],
 id:["Instal Swobu","Swobu belum terpasang di host ekstensi ini.","Swobu diperlukan untuk menyediakan model bahasa.","Tidak dapat mengunduh penginstal resmi Swobu (HTTP {0}).","Swobu belum siap. Periksa terminal Swobu untuk detailnya.","Berkas Swobu yang dikonfigurasi tidak ditemukan: {0}","Buat ruang kerja Swobu terlebih dahulu.","Ruang kerja untuk {0}"],
 ko:["Swobu 설치","이 확장 호스트에 Swobu가 설치되어 있지 않습니다.","언어 모델을 제공하려면 Swobu가 필요합니다.","공식 Swobu 설치 프로그램을 다운로드할 수 없습니다(HTTP {0}).","Swobu가 준비되지 않았습니다. 자세한 내용은 Swobu 터미널을 확인하세요.","구성된 Swobu 실행 파일을 찾을 수 없습니다: {0}","먼저 Swobu 작업 영역을 만드세요.","{0}용 작업 영역"],
 es:["Instalar Swobu","Swobu no está instalado en este host de extensiones.","Se necesita Swobu para proporcionar modelos de lenguaje.","No se pudo descargar el instalador oficial de Swobu (HTTP {0}).","Swobu no llegó a estar listo. Consulta el terminal de Swobu para obtener detalles.","No se encontró el ejecutable de Swobu configurado: {0}","Crea primero un espacio de trabajo de Swobu.","Espacio de trabajo para {0}"],
 de:["Swobu installieren","Swobu ist auf diesem Erweiterungshost nicht installiert.","Swobu wird benötigt, um Sprachmodelle bereitzustellen.","Das offizielle Swobu-Installationsprogramm konnte nicht heruntergeladen werden (HTTP {0}).","Swobu wurde nicht bereit. Details stehen im Swobu-Terminal.","Die konfigurierte Swobu-Programmdatei wurde nicht gefunden: {0}","Erstelle zuerst einen Swobu-Arbeitsbereich.","Arbeitsbereich für {0}"],
 fr:["Installer Swobu","Swobu n’est pas installé sur cet hôte d’extension.","Swobu est requis pour fournir des modèles de langage.","Impossible de télécharger le programme d’installation officiel de Swobu (HTTP {0}).","Swobu n’est pas devenu disponible. Consultez le terminal Swobu pour plus de détails.","L’exécutable Swobu configuré est introuvable : {0}","Créez d’abord un espace de travail Swobu.","Espace de travail pour {0}"],
 ru:["Установить Swobu","Swobu не установлен на этом узле расширения.","Для предоставления языковых моделей требуется Swobu.","Не удалось скачать официальный установщик Swobu (HTTP {0}).","Swobu не перешёл в состояние готовности. Подробности см. в терминале Swobu.","Настроенный исполняемый файл Swobu не найден: {0}","Сначала создайте рабочее пространство Swobu.","Рабочее пространство для {0}"],
 uk:["Установити Swobu","Swobu не встановлено на цьому вузлі розширення.","Для надання мовних моделей потрібен Swobu.","Не вдалося завантажити офіційний інсталятор Swobu (HTTP {0}).","Swobu не став готовим. Докладніше дивіться в терміналі Swobu.","Налаштований виконуваний файл Swobu не знайдено: {0}","Спочатку створіть робочий простір Swobu.","Робочий простір для {0}"]
};
for(const [locale,values]of Object.entries(added))translations[locale].push(...values);
const errors={
 "zh-cn":["Swobu 端点必须使用 HTTP 或 HTTPS。","Swobu 端点必须是环回地址。","Swobu 端点必须是不含凭据、路径、查询或片段的环回源。","配置的 Swobu 可执行文件必须是此扩展主机上的绝对路径。","Swobu 未返回响应流。","Swobu 连接命令退出，代码为 {0}。","Swobu 请求失败（HTTP {0}）。","不支持的 VS Code 语言模型部分：{0}。","不支持的 VS Code 消息角色。","不支持的数据部分：{0}。","不支持的工具结果部分。","模型公告应为布尔值。","模型公告应为正整数。","Swobu 返回了格式错误的流式 JSON。","函数调用缺少调用 ID。","工具参数先于对应的函数调用到达。","已完成的函数调用没有流式状态。","Swobu 请求失败。","流式工具事件缺少输出索引。"],
 ja:["Swobu エンドポイントは HTTP または HTTPS を使用する必要があります。","Swobu エンドポイントはループバックである必要があります。","Swobu エンドポイントは、資格情報、パス、クエリ、フラグメントを含まないループバックオリジンである必要があります。","設定する Swobu 実行ファイルは、この拡張機能ホスト上の絶対パスである必要があります。","Swobu から応答ストリームが返されませんでした。","Swobu 接続コマンドはコード {0} で終了しました。","Swobu リクエストに失敗しました（HTTP {0}）。","サポートされていない VS Code 言語モデルパートです：{0}。","サポートされていない VS Code メッセージロールです。","サポートされていないデータパートです：{0}。","サポートされていないツール結果パートです。","モデルの広告値には真偽値が必要です。","モデルの広告値には正の整数が必要です。","Swobu から不正なストリーミング JSON が返されました。","関数呼び出しに呼び出し ID がありません。","対応する関数呼び出しより先にツール引数が届きました。","完了した関数呼び出しにストリーミング状態がありません。","Swobu リクエストに失敗しました。","ストリーミングツールイベントに出力インデックスがありません。"],
 "pt-br":["O endpoint do Swobu deve usar HTTP ou HTTPS.","O endpoint do Swobu deve ser de loopback.","O endpoint do Swobu deve ser uma origem de loopback sem credenciais, caminho, consulta ou fragmento.","O executável Swobu configurado deve ter um caminho absoluto neste host de extensão.","O Swobu não retornou um fluxo de resposta.","A conexão do Swobu terminou com o código {0}.","A solicitação ao Swobu falhou (HTTP {0}).","Parte de modelo de linguagem do VS Code sem suporte: {0}.","Função de mensagem do VS Code sem suporte.","Parte de dados sem suporte: {0}.","Parte de resultado de ferramenta sem suporte.","Era esperado um anúncio de modelo booleano.","Era esperado um anúncio de modelo inteiro positivo.","O Swobu retornou JSON de streaming malformado.","A chamada de função não tem um ID de chamada.","Os argumentos da ferramenta chegaram antes da chamada de função.","A chamada de função concluída não tem estado de streaming.","A solicitação ao Swobu falhou.","O evento de ferramenta em streaming não tem índice de saída."],
 id:["Endpoint Swobu harus menggunakan HTTP atau HTTPS.","Endpoint Swobu harus berupa loopback.","Endpoint Swobu harus berupa asal loopback tanpa kredensial, jalur, kueri, atau fragmen.","Berkas Swobu yang dikonfigurasi harus menggunakan jalur absolut pada host ekstensi ini.","Swobu tidak mengembalikan aliran respons.","Koneksi Swobu berhenti dengan kode {0}.","Permintaan Swobu gagal (HTTP {0}).","Bagian model bahasa VS Code tidak didukung: {0}.","Peran pesan VS Code tidak didukung.","Bagian data tidak didukung: {0}.","Bagian hasil alat tidak didukung.","Iklan model harus berupa nilai boolean.","Iklan model harus berupa bilangan bulat positif.","Swobu mengembalikan JSON streaming yang rusak.","Panggilan fungsi tidak memiliki ID panggilan.","Argumen alat tiba sebelum panggilan fungsinya.","Panggilan fungsi yang selesai tidak memiliki status streaming.","Permintaan Swobu gagal.","Peristiwa alat streaming tidak memiliki indeks keluaran."],
 ko:["Swobu 엔드포인트는 HTTP 또는 HTTPS를 사용해야 합니다.","Swobu 엔드포인트는 루프백이어야 합니다.","Swobu 엔드포인트는 자격 증명, 경로, 쿼리 또는 프래그먼트가 없는 루프백 원본이어야 합니다.","구성된 Swobu 실행 파일은 이 확장 호스트의 절대 경로여야 합니다.","Swobu가 응답 스트림을 반환하지 않았습니다.","Swobu 연결이 코드 {0}(으)로 종료되었습니다.","Swobu 요청이 실패했습니다(HTTP {0}).","지원되지 않는 VS Code 언어 모델 부분: {0}.","지원되지 않는 VS Code 메시지 역할입니다.","지원되지 않는 데이터 부분: {0}.","지원되지 않는 도구 결과 부분입니다.","불리언 모델 공지가 필요합니다.","양의 정수 모델 공지가 필요합니다.","Swobu가 잘못된 스트리밍 JSON을 반환했습니다.","함수 호출에 호출 ID가 없습니다.","도구 인수가 해당 함수 호출보다 먼저 도착했습니다.","완료된 함수 호출에 스트리밍 상태가 없습니다.","Swobu 요청이 실패했습니다.","스트리밍 도구 이벤트에 출력 인덱스가 없습니다."],
 es:["El endpoint de Swobu debe usar HTTP o HTTPS.","El endpoint de Swobu debe ser de bucle local.","El endpoint de Swobu debe ser un origen de bucle local sin credenciales, ruta, consulta ni fragmento.","El ejecutable de Swobu configurado debe ser una ruta absoluta en este host de extensiones.","Swobu no devolvió ningún flujo de respuesta.","La conexión de Swobu terminó con el código {0}.","La solicitud a Swobu falló (HTTP {0}).","Parte de modelo de lenguaje de VS Code no compatible: {0}.","Rol de mensaje de VS Code no compatible.","Parte de datos no compatible: {0}.","Parte de resultado de herramienta no compatible.","Se esperaba un anuncio de modelo booleano.","Se esperaba un anuncio de modelo entero positivo.","Swobu devolvió JSON de transmisión con formato incorrecto.","A la llamada de función le falta el ID de llamada.","Los argumentos de la herramienta llegaron antes que su llamada de función.","La llamada de función completada no tiene estado de transmisión.","La solicitud a Swobu falló.","Al evento de herramienta en transmisión le falta el índice de salida."],
 de:["Der Swobu-Endpunkt muss HTTP oder HTTPS verwenden.","Der Swobu-Endpunkt muss eine Loopback-Adresse sein.","Der Swobu-Endpunkt muss ein Loopback-Ursprung ohne Zugangsdaten, Pfad, Abfrage oder Fragment sein.","Die konfigurierte Swobu-Programmdatei muss auf diesem Erweiterungshost einen absoluten Pfad haben.","Swobu hat keinen Antwortstream zurückgegeben.","Die Swobu-Verbindung wurde mit Code {0} beendet.","Die Swobu-Anfrage ist fehlgeschlagen (HTTP {0}).","Nicht unterstützter VS-Code-Sprachmodellteil: {0}.","Nicht unterstützte VS-Code-Nachrichtenrolle.","Nicht unterstützter Datenteil: {0}.","Nicht unterstützter Werkzeugergebnisteil.","Eine boolesche Modellangabe wurde erwartet.","Eine positive ganzzahlige Modellangabe wurde erwartet.","Swobu hat fehlerhaftes Streaming-JSON zurückgegeben.","Der Funktionsaufruf hat keine Aufruf-ID.","Werkzeugargumente trafen vor ihrem Funktionsaufruf ein.","Der abgeschlossene Funktionsaufruf hat keinen Streaming-Zustand.","Die Swobu-Anfrage ist fehlgeschlagen.","Dem Streaming-Werkzeugereignis fehlt der Ausgabeindex."],
 fr:["Le point de terminaison Swobu doit utiliser HTTP ou HTTPS.","Le point de terminaison Swobu doit être une adresse de bouclage.","Le point de terminaison Swobu doit être une origine de bouclage sans identifiants, chemin, requête ni fragment.","L’exécutable Swobu configuré doit être un chemin absolu sur cet hôte d’extension.","Swobu n’a renvoyé aucun flux de réponse.","La connexion Swobu s’est terminée avec le code {0}.","La requête Swobu a échoué (HTTP {0}).","Partie de modèle de langage VS Code non prise en charge : {0}.","Rôle de message VS Code non pris en charge.","Partie de données non prise en charge : {0}.","Partie de résultat d’outil non prise en charge.","Une annonce de modèle booléenne était attendue.","Une annonce de modèle entière positive était attendue.","Swobu a renvoyé un JSON de diffusion mal formé.","L’appel de fonction n’a pas d’identifiant d’appel.","Les arguments de l’outil sont arrivés avant leur appel de fonction.","L’appel de fonction terminé n’a aucun état de diffusion.","La requête Swobu a échoué.","L’événement d’outil diffusé n’a pas d’index de sortie."],
 ru:["Конечная точка Swobu должна использовать HTTP или HTTPS.","Конечная точка Swobu должна быть адресом обратной петли.","Конечная точка Swobu должна быть источником обратной петли без учётных данных, пути, запроса или фрагмента.","Настроенный исполняемый файл Swobu должен быть задан абсолютным путём на этом узле расширения.","Swobu не вернул поток ответа.","Подключение Swobu завершилось с кодом {0}.","Запрос Swobu завершился ошибкой (HTTP {0}).","Неподдерживаемая часть языковой модели VS Code: {0}.","Неподдерживаемая роль сообщения VS Code.","Неподдерживаемая часть данных: {0}.","Неподдерживаемая часть результата инструмента.","Ожидалось логическое объявление модели.","Ожидалось объявление модели в виде положительного целого числа.","Swobu вернул некорректный потоковый JSON.","У вызова функции отсутствует идентификатор вызова.","Аргументы инструмента поступили до вызова соответствующей функции.","У завершённого вызова функции отсутствует потоковое состояние.","Запрос Swobu завершился ошибкой.","У потокового события инструмента отсутствует индекс вывода."],
 uk:["Кінцева точка Swobu має використовувати HTTP або HTTPS.","Кінцева точка Swobu має бути адресою зворотного зв’язку.","Кінцева точка Swobu має бути джерелом зворотного зв’язку без облікових даних, шляху, запиту чи фрагмента.","Налаштований виконуваний файл Swobu має бути заданий абсолютним шляхом на цьому вузлі розширення.","Swobu не повернув потік відповіді.","Підключення Swobu завершилося з кодом {0}.","Запит Swobu завершився помилкою (HTTP {0}).","Непідтримувана частина мовної моделі VS Code: {0}.","Непідтримувана роль повідомлення VS Code.","Непідтримувана частина даних: {0}.","Непідтримувана частина результату інструмента.","Очікувалося логічне оголошення моделі.","Очікувалося оголошення моделі як додатного цілого числа.","Swobu повернув некоректний потоковий JSON.","У виклику функції немає ідентифікатора виклику.","Аргументи інструмента надійшли до виклику відповідної функції.","Завершений виклик функції не має потокового стану.","Запит Swobu завершився помилкою.","У потоковій події інструмента немає індексу виводу."]
};
for(const [locale,values]of Object.entries(errors)){if(values.length!==errorKeys.length)throw new Error(`Missing ${locale} error strings`);translations[locale].push(...values);}
const remainingKeys=["Swobu control plane returned HTTP {0}.","Swobu control-plane protocol {0} is incompatible; this extension requires {1}.","missing","This extension requires Swobu {0} or newer; found {1}.","an unknown version","Swobu route {0} in {1}.","Swobu: Connect {0}","unknown","Required tool mode requires at least one declared tool.","Swobu endpoint must be a valid URL.","Unsupported streamed output item: {0}.","Named VS Code messages are not supported.","Function call is missing its name.","Function call arguments must be a JSON object."];
keys.push(...remainingKeys);
const remaining={
 "zh-cn":["Swobu 控制平面返回了 HTTP {0}。","Swobu 控制平面协议 {0} 不兼容；此扩展需要 {1}。","缺失","此扩展需要 Swobu {0} 或更高版本；当前为 {1}。","未知版本","Swobu 路由 {0}（工作区 {1}）。","Swobu：连接 {0}","未知","必需工具模式要求至少声明一个工具。","Swobu 端点必须是有效的 URL。","不支持的流式输出项：{0}。","不支持带名称的 VS Code 消息。","函数调用缺少名称。","函数调用参数必须是 JSON 对象。"],
 ja:["Swobu コントロールプレーンが HTTP {0} を返しました。","Swobu コントロールプレーンプロトコル {0} は互換性がありません。この拡張機能には {1} が必要です。","なし","この拡張機能には Swobu {0} 以降が必要です。検出されたバージョン：{1}。","不明なバージョン","Swobu ルート {0}（ワークスペース {1}）。","Swobu: {0} に接続","不明","必須ツールモードには、宣言済みのツールが少なくとも 1 つ必要です。","Swobu エンドポイントは有効な URL である必要があります。","サポートされていないストリーミング出力項目です：{0}。","名前付きの VS Code メッセージはサポートされていません。","関数呼び出しに名前がありません。","関数呼び出しの引数は JSON オブジェクトである必要があります。"],
 "pt-br":["O plano de controle do Swobu retornou HTTP {0}.","O protocolo {0} do plano de controle do Swobu é incompatível; esta extensão requer {1}.","ausente","Esta extensão requer o Swobu {0} ou mais recente; encontrado {1}.","uma versão desconhecida","Rota Swobu {0} em {1}.","Swobu: conectar {0}","desconhecido","O modo de ferramenta obrigatório requer pelo menos uma ferramenta declarada.","O endpoint do Swobu deve ser uma URL válida.","Item de saída em streaming sem suporte: {0}.","Mensagens nomeadas do VS Code não são compatíveis.","A chamada de função não tem nome.","Os argumentos da chamada de função devem ser um objeto JSON."],
 id:["Bidang kontrol Swobu mengembalikan HTTP {0}.","Protokol bidang kontrol Swobu {0} tidak kompatibel; ekstensi ini memerlukan {1}.","tidak ada","Ekstensi ini memerlukan Swobu {0} atau yang lebih baru; ditemukan {1}.","versi yang tidak diketahui","Rute Swobu {0} di {1}.","Swobu: Hubungkan {0}","tidak diketahui","Mode alat wajib memerlukan setidaknya satu alat yang dideklarasikan.","Endpoint Swobu harus berupa URL yang valid.","Item keluaran streaming tidak didukung: {0}.","Pesan VS Code bernama tidak didukung.","Panggilan fungsi tidak memiliki nama.","Argumen panggilan fungsi harus berupa objek JSON."],
 ko:["Swobu 제어 영역이 HTTP {0}을(를) 반환했습니다.","Swobu 제어 영역 프로토콜 {0}은(는) 호환되지 않습니다. 이 확장에는 {1}이(가) 필요합니다.","없음","이 확장에는 Swobu {0} 이상이 필요합니다. 발견된 버전: {1}.","알 수 없는 버전","Swobu 경로 {0}(워크스페이스 {1}).","Swobu: {0} 연결","알 수 없음","필수 도구 모드에는 선언된 도구가 하나 이상 필요합니다.","Swobu 엔드포인트는 유효한 URL이어야 합니다.","지원되지 않는 스트리밍 출력 항목: {0}.","이름이 지정된 VS Code 메시지는 지원되지 않습니다.","함수 호출에 이름이 없습니다.","함수 호출 인수는 JSON 객체여야 합니다."],
 es:["El plano de control de Swobu devolvió HTTP {0}.","El protocolo {0} del plano de control de Swobu no es compatible; esta extensión requiere {1}.","ausente","Esta extensión requiere Swobu {0} o posterior; se encontró {1}.","una versión desconocida","Ruta Swobu {0} en {1}.","Swobu: conectar {0}","desconocido","El modo de herramienta obligatorio requiere al menos una herramienta declarada.","El endpoint de Swobu debe ser una URL válida.","Elemento de salida en streaming no compatible: {0}.","No se admiten mensajes de VS Code con nombre.","La llamada a función no tiene nombre.","Los argumentos de la llamada a función deben ser un objeto JSON."],
 de:["Die Swobu-Steuerungsebene hat HTTP {0} zurückgegeben.","Das Swobu-Steuerungsprotokoll {0} ist inkompatibel; diese Erweiterung benötigt {1}.","fehlt","Diese Erweiterung benötigt Swobu {0} oder neuer; gefunden wurde {1}.","eine unbekannte Version","Swobu-Route {0} in {1}.","Swobu: {0} verbinden","unbekannt","Der erforderliche Werkzeugmodus benötigt mindestens ein deklariertes Werkzeug.","Der Swobu-Endpunkt muss eine gültige URL sein.","Nicht unterstütztes Streaming-Ausgabeelement: {0}.","Benannte VS-Code-Nachrichten werden nicht unterstützt.","Dem Funktionsaufruf fehlt der Name.","Die Argumente des Funktionsaufrufs müssen ein JSON-Objekt sein."],
 fr:["Le plan de contrôle Swobu a renvoyé HTTP {0}.","Le protocole {0} du plan de contrôle Swobu est incompatible ; cette extension requiert {1}.","absent","Cette extension requiert Swobu {0} ou une version ultérieure ; version trouvée : {1}.","une version inconnue","Route Swobu {0} dans {1}.","Swobu : connecter {0}","inconnu","Le mode d’outil obligatoire nécessite au moins un outil déclaré.","Le point de terminaison Swobu doit être une URL valide.","Élément de sortie diffusé non pris en charge : {0}.","Les messages VS Code nommés ne sont pas pris en charge.","Le nom de l’appel de fonction est manquant.","Les arguments de l’appel de fonction doivent être un objet JSON."],
 ru:["Плоскость управления Swobu вернула HTTP {0}.","Протокол плоскости управления Swobu {0} несовместим; расширению требуется {1}.","отсутствует","Расширению требуется Swobu {0} или новее; обнаружено: {1}.","неизвестная версия","Маршрут Swobu {0} в {1}.","Swobu: подключить {0}","неизвестно","Режим обязательного инструмента требует хотя бы одного объявленного инструмента.","Конечная точка Swobu должна быть допустимым URL.","Неподдерживаемый элемент потокового вывода: {0}.","Именованные сообщения VS Code не поддерживаются.","У вызова функции отсутствует имя.","Аргументы вызова функции должны быть объектом JSON."],
 uk:["Площина керування Swobu повернула HTTP {0}.","Протокол площини керування Swobu {0} несумісний; розширенню потрібен {1}.","відсутній","Розширенню потрібен Swobu {0} або новіший; знайдено: {1}.","невідома версія","Маршрут Swobu {0} у {1}.","Swobu: підключити {0}","невідомо","Режим обов’язкового інструмента потребує щонайменше одного оголошеного інструмента.","Кінцева точка Swobu має бути дійсною URL-адресою.","Непідтримуваний елемент потокового виводу: {0}.","Іменовані повідомлення VS Code не підтримуються.","У виклику функції немає назви.","Аргументи виклику функції мають бути об’єктом JSON."]
};
for(const [locale,values]of Object.entries(remaining)){if(values.length!==remainingKeys.length)throw new Error(`Missing ${locale} remaining strings`);translations[locale].push(...values);}
const configuration={
 endpoint:"Swobu daemon endpoint.",
 executable:"Optional absolute path to a compatible Swobu executable on this extension host. The normal PATH installation is used when empty.",
 modelOverrides:"Capability and token-limit overrides keyed by <workspace>/<route>."
};
const localizedConfiguration={
 "zh-cn":{endpoint:"Swobu 守护进程端点。",executable:"可选：此扩展主机上兼容 Swobu 可执行文件的绝对路径。留空时使用 PATH 中的常规安装。",modelOverrides:"按 <workspace>/<route> 键控的功能和令牌限制覆盖。"},
 ja:{endpoint:"Swobu デーモンのエンドポイント。",executable:"この拡張機能ホスト上の互換性のある Swobu 実行ファイルへの絶対パス（省略可）。空の場合は通常の PATH インストールを使用します。",modelOverrides:"<workspace>/<route> をキーとする機能とトークン上限のオーバーライド。"},
 "pt-br":{endpoint:"Endpoint do daemon do Swobu.",executable:"Caminho absoluto opcional para um executável Swobu compatível neste host de extensão. Quando vazio, usa a instalação normal no PATH.",modelOverrides:"Substituições de recursos e limites de tokens identificadas por <workspace>/<route>."},
 id:{endpoint:"Endpoint daemon Swobu.",executable:"Jalur absolut opsional ke berkas Swobu yang kompatibel pada host ekstensi ini. Jika kosong, instalasi normal di PATH akan digunakan.",modelOverrides:"Pengesampingan kemampuan dan batas token dengan kunci <workspace>/<route>."},
 ko:{endpoint:"Swobu 데몬 엔드포인트입니다.",executable:"이 확장 호스트에서 호환되는 Swobu 실행 파일의 선택적 절대 경로입니다. 비어 있으면 PATH의 일반 설치를 사용합니다.",modelOverrides:"<workspace>/<route> 키별 기능 및 토큰 한도 재정의입니다."},
 es:{endpoint:"Endpoint del daemon de Swobu.",executable:"Ruta absoluta opcional a un ejecutable de Swobu compatible en este host de extensiones. Si se deja vacía, se usa la instalación normal del PATH.",modelOverrides:"Sustituciones de capacidades y límites de tokens identificadas por <workspace>/<route>."},
 de:{endpoint:"Endpunkt des Swobu-Daemons.",executable:"Optionaler absoluter Pfad zu einer kompatiblen Swobu-Programmdatei auf diesem Erweiterungshost. Ist das Feld leer, wird die normale Installation im PATH verwendet.",modelOverrides:"Funktions- und Tokenlimitüberschreibungen mit dem Schlüssel <workspace>/<route>."},
 fr:{endpoint:"Point de terminaison du daemon Swobu.",executable:"Chemin absolu facultatif vers un exécutable Swobu compatible sur cet hôte d’extension. Si le champ est vide, l’installation normale du PATH est utilisée.",modelOverrides:"Remplacements de capacités et de limites de jetons indexés par <workspace>/<route>."},
 ru:{endpoint:"Конечная точка демона Swobu.",executable:"Необязательный абсолютный путь к совместимому исполняемому файлу Swobu на этом узле расширения. Если поле пусто, используется обычная установка из PATH.",modelOverrides:"Переопределения возможностей и ограничений токенов с ключом <workspace>/<route>."},
 uk:{endpoint:"Кінцева точка демона Swobu.",executable:"Необов’язковий абсолютний шлях до сумісного виконуваного файлу Swobu на цьому вузлі розширення. Якщо поле порожнє, використовується звичайне встановлення з PATH.",modelOverrides:"Перевизначення можливостей і обмежень токенів із ключем <workspace>/<route>."}
};
const metadata={displayName:"LLM Router for VS Code, Claude Code & Codex — Swobu",description:"Keep VS Code Agent, Claude Code and Codex. Route model requests through your local Swobu endpoint with provider choice and fallback."};
const localizedMetadata={
 "zh-cn":{displayName:"VS Code、Claude Code 与 Codex 的 LLM 路由器 — Swobu",description:"保留 VS Code Agent、Claude Code 和 Codex。通过本地 Swobu 端点路由模型请求，并选择提供商和备用方案。"},
 ja:{displayName:"VS Code、Claude Code、Codex 向け LLM ルーター — Swobu",description:"VS Code Agent、Claude Code、Codex はそのまま。ローカルの Swobu エンドポイント経由でモデルリクエストをルーティングし、プロバイダーとフォールバックを選べます。"},
 "pt-br":{displayName:"Roteador LLM para VS Code, Claude Code e Codex — Swobu",description:"Continue usando VS Code Agent, Claude Code e Codex. Encaminhe solicitações de modelo pelo endpoint Swobu local com escolha de provedor e alternativa."},
 id:{displayName:"Router LLM untuk VS Code, Claude Code, dan Codex — Swobu",description:"Tetap gunakan VS Code Agent, Claude Code, dan Codex. Rutekan permintaan model melalui endpoint Swobu lokal dengan pilihan penyedia dan fallback."},
 ko:{displayName:"VS Code, Claude Code 및 Codex용 LLM 라우터 — Swobu",description:"VS Code Agent, Claude Code 및 Codex를 그대로 사용하세요. 로컬 Swobu 엔드포인트를 통해 모델 요청을 라우팅하고 제공자와 대체 경로를 선택하세요."},
 es:{displayName:"Enrutador LLM para VS Code, Claude Code y Codex — Swobu",description:"Conserva VS Code Agent, Claude Code y Codex. Enruta las solicitudes de modelos por tu endpoint Swobu local con selección de proveedor y alternativa."},
 de:{displayName:"LLM-Router für VS Code, Claude Code und Codex — Swobu",description:"Behalte VS Code Agent, Claude Code und Codex. Leite Modellanfragen über deinen lokalen Swobu-Endpunkt und wähle Anbieter und Fallback."},
 fr:{displayName:"Routeur LLM pour VS Code, Claude Code et Codex — Swobu",description:"Gardez VS Code Agent, Claude Code et Codex. Acheminez les requêtes de modèles via votre point de terminaison Swobu local avec le fournisseur et le repli de votre choix."},
 ru:{displayName:"Маршрутизатор LLM для VS Code, Claude Code и Codex — Swobu",description:"Продолжайте использовать VS Code Agent, Claude Code и Codex. Направляйте запросы к моделям через локальную конечную точку Swobu с выбором поставщика и резервного варианта."},
 uk:{displayName:"Маршрутизатор LLM для VS Code, Claude Code та Codex — Swobu",description:"Продовжуйте використовувати VS Code Agent, Claude Code та Codex. Спрямовуйте запити до моделей через локальну кінцеву точку Swobu з вибором постачальника й резервного варіанта."}
};
mkdirSync("l10n",{recursive:true});
const write=(path,value)=>writeFileSync(path,JSON.stringify(value,null,2)+"\n");
write("l10n/bundle.l10n.json",Object.fromEntries(keys.map(key=>[key,key])));
const pkg=JSON.parse(readFileSync("package.json"));const commands=["Open","Set Up","Connect Claude Code","Connect Codex","Configure Model","Refresh Models"];
pkg.displayName="%displayName%";pkg.description="%description%";
for(let i=0;i<commands.length;i++)pkg.contributes.commands[i].title=`%command.${i}%`;
write("package.nls.json",{displayName:metadata.displayName,description:metadata.description,...Object.fromEntries(commands.map((key,i)=>[`command.${i}`,key])),"configuration.endpoint.description":configuration.endpoint,"configuration.executable.description":configuration.executable,"configuration.modelOverrides.description":configuration.modelOverrides});
for(const [locale,values]of Object.entries(translations)){if(values.length!==keys.length)throw new Error(`Missing ${locale} strings`);const localized=localizedConfiguration[locale],localizedMeta=localizedMetadata[locale];if(!localized||!localizedMeta)throw new Error(`Missing ${locale} manifest strings`);write(`l10n/bundle.l10n.${locale}.json`,Object.fromEntries(keys.map((key,i)=>[key,values[i]])));write(`package.nls.${locale}.json`,{displayName:localizedMeta.displayName,description:localizedMeta.description,...Object.fromEntries(commands.map((_,i)=>[`command.${i}`,values[i]])),"configuration.endpoint.description":localized.endpoint,"configuration.executable.description":localized.executable,"configuration.modelOverrides.description":localized.modelOverrides});}
write("package.json",pkg);
